---
title: "Revised Regression"
author: "Evan Dragich"
date: "Last compiled on `r Sys.Date()`"
output:
  pdf_document: default
  html_document:
    df_print: paged
urlcolor: blue
---

```{r include = FALSE}
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE)
```


# Data Cleaning

```{r load-packages-data, echo = FALSE}
library(readxl) # tidy import of xlsx
library(writexl) # write to xlsx file
library(tidyverse) # dplyr, magrittr
library(ordinal) # clmm() for ordinal regression
library(RVAideMemoire) # Anova.clm()
library(emmeans) # mean class and contrasts


# clean individual datasets into tidy format
mass_2019 <- read_excel(here::here("data_mass_only_from_2019_folder.xlsx"),
  sheet = "mass balances"
) %>%
  dplyr::select(-c(...2, ...3)) %>%
  drop_na(...1) %>%
  mutate(task = c(rep("lec", 6), rep("icp", 6), rep("hw", 6), rep("pbl", 12))) %>%
  rename(blooms_level = `...1`) %>%
  pivot_longer(
    cols = where(is.numeric),
    names_to = "student_id",
    values_to = "rating"
  ) %>%
  mutate(
    year = "2019",
    student_id = str_to_lower(student_id)
  ) # 2019 student ids will be lowercase; 2020 uppercase

kinetics_2019 <- read_excel(here::here("data_kinetics_from_2019_folder.xlsx"),
  sheet = "kinetics"
) %>%
  dplyr::select(-c(...2, ...3)) %>%
  drop_na(...1) %>%
  slice_head(n = 24) %>% # remove irrelevant PBL1 data
  mutate(task = c(rep("lec", 6), rep("icp", 6), rep("hw", 6), rep("pbl", 6))) %>%
  rename(blooms_level = `...1`) %>%
  pivot_longer(
    cols = where(is.numeric),
    names_to = "student_id",
    values_to = "rating"
  ) %>%
  mutate(
    year = "2019",
    student_id = str_to_lower(student_id)
  )

# 2020 didnt come with student id letter codes, so I'm making them here
# same sequence as 2019, but all caps to distinguish
helper_letters <- c(LETTERS, paste0(LETTERS, LETTERS)) %>%
  .[1:48]

mass_2020 <- read_excel(here::here("combined_2020.xlsx"),
  sheet = "Mass"
)

names(mass_2020) <- c("blooms_level", helper_letters)

mass_2020 <- mass_2020 %>%
  drop_na(A) %>%
  mutate(task = c(rep("lec", 6), rep("icp", 6), rep("hw", 6), rep("pbl", 12))) %>%
  pivot_longer(
    cols = where(is.numeric),
    names_to = "student_id",
    values_to = "rating"
  ) %>%
  mutate(year = "2020",
         blooms_level = str_to_lower(blooms_level))

kinetics_2020 <- read_excel(here::here("combined_2020.xlsx"),
  sheet = "Kinetics"
)

names(kinetics_2020) <- c("blooms_level", helper_letters)

kinetics_2020 <- kinetics_2020 %>%
  drop_na(A) %>%
  dplyr::slice(c(1:18, 25:30)) %>% # remove irrelevant PBL1 data
  mutate(task = c(rep("lec", 6), rep("icp", 6), rep("hw", 6), rep("pbl", 6))) %>%
  pivot_longer(
    cols = where(is.numeric),
    names_to = "student_id",
    values_to = "rating"
  ) %>%
  mutate(year = "2020",
         blooms_level = str_to_lower(blooms_level))

```

```{r combine-years, echo = FALSE}
# create final dataframes for each domain
mass <- rbind(mass_2019, mass_2020) %>%
  mutate(
    student_id = factor(student_id),
    year = factor(year),
    blooms_level = factor(blooms_level, 
                          levels = c("remember", "understand", "analyze", 
                                     "apply", "evaluate", "create")),
    task = factor(task, levels = c("lec", "icp", "hw", "pbl"))
  )

kinetics <- rbind(kinetics_2019, kinetics_2020) %>%
  mutate(
    student_id = factor(student_id),
    year = factor(year),
    blooms_level = factor(blooms_level, 
                          levels = c("remember", "understand", "analyze", 
                                     "apply", "evaluate", "create")),
    task = factor(task, levels = c("lec", "icp", "hw", "pbl"))
  )
```

# Mass Analysis

## Omnibus ANOVA

```{r mass-lmm}
mass <- mass %>%
  mutate(rating = factor(rating, ordered = TRUE))

mass_clmm <- clmm(rating ~ blooms_level * task + year + (1 | student_id), data = mass)

summary(mass_clmm)

Anova.clmm(mass_clmm)

# null model to test significance of random effects
mass_null <- clm(rating ~ blooms_level * task, data = mass)
anova(mass_clmm, mass_null)

```


## Marginal Means and Contrasts

``` {r mass-emmeans}
# split by task, then compares pairs of blooms levels
mass_emm_t <- emmeans(mass_clmm, specs = pairwise ~ blooms_level | task, mode = "mean.class")

mass_task_means <- mass_emm_t$emmeans %>%
  summary(infer = TRUE, null = mean(as.numeric(mass$rating), na.rm = TRUE), level = 0.95, adjust = "bonferroni")
mass_task_contrasts <-mass_emm_t$contrasts %>%
  summary(infer = TRUE, level = 0.95, adjust = "bonferroni")

# split by blooms level, then compares pairs of tasks
mass_emm_bl <- emmeans(mass_clmm, specs = pairwise ~ task | blooms_level, mode = "mean.class")

mass_bl_means <- mass_emm_bl$emmeans %>%
  summary(infer = TRUE, null = mean(as.numeric(mass$rating), na.rm = TRUE), level = 0.95, adjust = "bonferroni")
mass_bl_contrasts <- mass_emm_bl$contrasts %>%
  summary(infer = TRUE, level = 0.95, adjust = "bonferroni")
```

# Kinetics Analysis

## Omnibus ANOVA


```{r kinetics-lmm}
kinetics <- kinetics %>%
  mutate(rating = factor(rating, ordered = TRUE))

kinetics_clmm <- clmm(rating ~ blooms_level * task + year + (1 | student_id), data = kinetics)

summary(kinetics_clmm)
Anova.clmm(kinetics_clmm)

# null model to test significance of fixed effects
kinetics_null <- clm(rating ~ blooms_level * task + year, data = kinetics)
anova(kinetics_clmm, kinetics_null)

```

## Estimated Marginal Means and Contrasts

``` {r kinetics-emmeans}
kinetics_emm_t <- emmeans(kinetics_clmm, specs = pairwise ~ blooms_level | task, mode = "mean.class")

kinetics_task_means <- kinetics_emm_t$emmeans %>%
  summary(infer = TRUE, null = mean(as.numeric(kinetics$rating), na.rm = TRUE), level = 0.95, adjust = "bonferroni")
kinetics_task_contrasts <-kinetics_emm_t$contrasts %>%
  summary(infer = TRUE, level = 0.95, adjust = "bonferroni")


kinetics_emm_bl <- emmeans(kinetics_clmm, specs = pairwise ~ task | blooms_level, mode = "mean.class")

kinetics_bl_means <- kinetics_emm_bl$emmeans %>%
  summary(infer = TRUE, null = mean(as.numeric(kinetics$rating), na.rm = TRUE), level = 0.95, adjust = "bonferroni")
kinetics_bl_contrasts <- kinetics_emm_bl$contrasts %>%
  summary(infer = TRUE, level = 0.95, adjust = "bonferroni")
```

## Write results to xlsx

```{r write-csv}

write_xlsx(list("Mass by Bloom's -  Mean Classes" = mass_bl_means,
                "Mass by Bloom's -  Contrasts" = mass_bl_contrasts,
                "Mass by Task -  Mean Classes" = mass_task_means,
                "Mass by Task -  Contrasts" = mass_task_contrasts,
                "Kinetics by Bloom's -  Mean Classes" = kinetics_bl_means,
                "Kinetics by Bloom's -  Contrasts" = kinetics_bl_contrasts,
                "Kinetics by Task -  Mean Classes" = kinetics_task_means,
                "Kinetics by Task -  Contrasts" = kinetics_task_contrasts),
            "clmm_anova_output.xlsx")
```

```{r session-info}
# information about this R session:
sessionInfo()
```

